version: "3"
services:
   backend:
     image: app:latest
     ports:
       - "5000:5000"
     environment:
       MYSQL_HOST: 192.168.1.90
       MYSQL_USER: admin
       MYSQL_PASSWORD: 1234
       MYSQL_DB: myDb
     depends_on:
       - mysql
   
   mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - data:/var/lib/mysql

volumes:
  data:  
