version: "3.9"
services:
   backend:
     container_name: webapp
     build: .  
     networks:
       - jet
     ports:
       - "5000:5000"
     environment:
       MYSQL_HOST: 192.168.1.151
       MYSQL_USER: admin
       MYSQL_PASSWORD: 1234
       MYSQL_DB: myDb
     depends_on:
       - mysql
   
   mysql:
    container_name: mysql
    image: mysql:latest
    networks:
      - jet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - data:/var/lib/mysql

volumes:
  data:  

networks:
  jet:
